apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
          kubectl.kubernetes.io/restartedAt: '2025-01-02T20:32:45Z'
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: simonjan2/project-management:server
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: project-management-config
              key: MONGO_URI
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: project-management-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: project-management-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: project-management-secret
              key: JWT_SECRET
        - name: JWT_EXPIRE
          valueFrom:
            secretKeyRef:
              name: project-management-secret
              key: JWT_EXPIRE
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
