apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-service-reader
subjects:
- kind: ServiceAccount
  name: frontend-sa
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
