name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_SERVER: simonjan2/project-management
  DOCKER_IMAGE_CLIENT: simonjan2/project-management

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_SERVER }}:server
            ${{ env.DOCKER_IMAGE_SERVER }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_SERVER }}:server
          cache-to: type=inline

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_CLIENT }}:client
            ${{ env.DOCKER_IMAGE_CLIENT }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_CLIENT }}:client
          cache-to: type=inline