name: Docker Build and Push
on:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE_SERVER: simonjan2/project-management
  DOCKER_IMAGE_CLIENT: simonjan2/project-management
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git first
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git config --global pull.rebase true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_SERVER }}:server
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_SERVER }}:server
          cache-to: type=inline

      - name: Update kubernetes manifests
        run: |
          git pull origin main
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          sed -i "s|kubectl.kubernetes.io/restartedAt: '.*'|kubectl.kubernetes.io/restartedAt: '$timestamp'|" k8s/backend.yaml
          git add k8s/backend.yaml
          git commit -m "Update backend deployment timestamp for new image" || echo "No changes to commit"
          git push origin main

  build-client:
    needs: [build-server]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git first
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git config --global pull.rebase true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_CLIENT }}:client
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_CLIENT }}:client
          cache-to: type=inline

      - name: Update kubernetes manifests
        run: |
          git pull origin main
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          sed -i "s|kubectl.kubernetes.io/restartedAt: '.*'|kubectl.kubernetes.io/restartedAt: '$timestamp'|" k8s/frontend.yaml
          git add k8s/frontend.yaml
          git commit -m "Update frontend deployment timestamp for new image" || echo "No changes to commit"
          git push origin main